config/routes.rb
# == Route Map
#
#     Prefix Verb   URI Pattern                         Controller#Action
#       root GET    /                                   pages#home
#      users GET    /users(.:format)                    users#index
#            POST   /users(.:format)                    users#create
#   new_user GET    /users/new(.:format)                users#new
#  edit_user GET    /users/:id/edit(.:format)           users#edit
#       user GET    /users/:id(.:format)                users#show
#            PATCH  /users/:id(.:format)                users#update
#            PUT    /users/:id(.:format)                users#update
#            DELETE /users/:id(.:format)                users#destroy
#    stories GET    /stories(.:format)                  stories#index
#            POST   /stories(.:format)                  stories#create
#  new_story GET    /stories/new(.:format)              stories#new
# edit_story GET    /stories/:id/edit(.:format)         stories#edit
#      story GET    /stories/:id(.:format)              stories#show
#            PATCH  /stories/:id(.:format)              stories#update
#            PUT    /stories/:id(.:format)              stories#update
#            DELETE /stories/:id(.:format)              stories#destroy
#       like GET    /stories/:id/like/:whisky(.:format) likes#like
#     unlike GET    /stories/:id/unlike(.:format)       likes#unlike
#      login GET    /login(.:format)                    session#new
#            POST   /login(.:format)                    session#create
#            DELETE /login(.:format)                    session#destroy
#

Rails.application.routes.draw do
    root :to => 'pages#home'


    get 'users/edit' =>'users#edit', :as =>'edit_user'  # you can not edit others' profile
    resources :users, :except =>[:edit]   #route generator

    resources :stories
    get '/user/:id/stories/' => 'stoies#index', :as =>'user_stories'


    post '/stories/:id/like' => 'stories#like', :as =>'like'
    post '/stories/:id/unlike' => 'stories#unlike', :as =>'unlike'


    get '/login' => 'session#new'
    post '/login' => 'session#create'
    delete '/login' => 'session#destroy'

end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  story_id   :integer
#  whisky     :boolean
#

class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :story
    validates_uniqueness_of :story_id, :scope => :user_id # Magic
end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Story < ActiveRecord::Base
    belongs_to :user
    has_many :likes
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :stories
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
  def fetch_user
  # Search for a user by their user id if we can find one in the session hash.
    if session[:user_id].present?
      @current_user = User.find_by :id => session[:user_id]

      # Clear out the session user_id if no user is found.
      session[:user_id] = nil unless @current_user
    end
  end
end

app/controllers/concerns/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_action :get_story, only: [:edit, :show, :update, :destroy, :like, :unlike, :whisky]
  before_action :authorise_user, except: [:index, :show]  # anyone can see the index of all stories

  def index
    # if params[:id].present?
    #   @stories = User.find(params[:id]).stories
    # else
      @stories = Story.all
    # end
  end

  def new
      @story = Story.new
  end


  def create
    story = Story.new story_params
    ip_address = request.ip
    story.address = Geocoder.search(ip_address).first.city
    story.user_id = @current_user.id
    if story.save
      redirect_to story
    else
      render :new
    end
    # Story.create = Story.new then save
    # Story.update = setting the parameters then call save
  end

  def edit
  end

  def update
    @story.update story_params
    redirect_to @story   #implicitly pointing to this instance, same story_path(@story.id)
  end

  def show
  end


  def destroy
    @story.destroy
    redirect_to stories_path
  end


  def like
    Like.create story_id: @story.id, user_id: @current_user.id #, whisky: params[:whisky]
    UserMailer.send_whisky(@current_user, @story.user).deliver_now
    redirect_to @story
  end

  def unlike
    Like.find_by(story_id: @story.id, user_id: @current_user.id).destroy
    redirect_to @story
  end


  private
    def story_params
      params.require(:story).permit(:title, :content, :address)
    end

    def get_story
      @story = Story.find params[:id]
    end

    def authorise_user
      redirect_to login_path unless @current_user.present?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorise_user, :only => [:index]
  before_action :check_for_user, :only => [:edit, :update]

  def new
    @user = User.new
  end


  def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
  end


  def index
    @users = User.all
  end


  def edit
    @user = @current_user  # can only edit/update  the current user, close the security hole  make url as users/edit, not showing the id
  end

  def show
      @user = @current_user
  end



  def update
    @user = @current_user    # can only edit/update  the current user, close the security hole

    if @user.update user_params
      redirect_to root_path
    else
      render :edit
    end
  end



  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def authorise_user
      redirect_to root_path unless @current_user.present? && @current_user.admin?
    end

    def check_for_user
      redirect_to new_user_path unless @current_user.present?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storiesforwhiskies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <link rel="stylesheet" type="text/css"
         href="https://fonts.googleapis.com/css?family=Tangerine">
</head>
<body>

<!-- <nav>
<a href="<%= root_path %>">Home</a>
<a href="<%= new_user_path  %>">New User</a>
</nav> -->



<nav class= "navbar navbar-inverse ">
  <ul class = "nav navbar-nav">

  <li><%= link_to 'HOME', root_path %></li>
  <% if @current_user.present? %>

    <%# if @current_user.admin? %>
      <%#= link_to "Users", users_path %>
    <%# end %>

    <!-- edit_use_path is static now, need to add a show page for this  -->
    <!-- <%= link_to "Edit Profile", edit_user_path %> -->

    <li><%= link_to "Logout", login_path, :method => :delete %></li>
    <li><%= link_to "My account", user_path(@current_user)%></li>
  <% else %>
    <li><%= link_to 'SIGN UP', new_user_path %></li>
    <li><%= link_to 'LOGIN', login_path %></li>
  <% end %>
</ul>
</nav>

<div class = "container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
    <div class="home">
        <h1 class ="homepagetext">Stories for whiskies </h1>

        <h2>我有故事，你有酒吗?</h2>

      </br>

      </br>
        <p><a href ="/stories/new" class="style2" ><button type="button"> I have stories to trade your Whiskies</a></button></p>
        <p><a href ="/stories" class="style2"> <button type="button"> I have Whiskies to trade your stories</a></button></p>


    </div>

    <div class ="home-image">
      <%= image_tag("scotch.jpg")%>
    </div>
  </br>

app/views/session/new.html.erb
<div class=" log-in col-xs-4 col-xs-offset-4">

<h2>Login <span class="glyphicon glyphicon-glass"></span></h2>

<%= form_tag '/login'  do %>

<div class ="form-group">
  <%= label_tag :username, nil, :autofocus => true %>
  <%= text_field_tag :name, nil, :class => 'form-control' %>
</div>

<div class ="form-group">
  <%= label_tag :email, nil, :autofocus => true %>
  <%= text_field_tag :email, nil, :class => 'form-control' %>
</div>

<div class ="form-group">
  <%= label_tag :password %>
  <%= password_field_tag :password, :class => 'form-control' %>
</div>

  <%= submit_tag 'Login', :class => "btn btn-danger" %>
<% end %>

</div>

app/views/stories/edit.html.erb
<div class="edit-story col-xs-4 col-xs-offset-4">


<h2>Edit Story</h2>



<%= form_for @story, html: {class:"form-horizontal"}  do |f|  %>
  <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true, :required => true, :placeholder =>"Title" %>
</div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :required => true, :placeholder =>"Enter your story here",:class =>"form-control",:rows =>"15" %>
 </div>

  <div class="form-group">
    <%= f.submit "edit this story", :class =>"btn btn-danger" %>
  </div>
<% end %>

</div>

app/views/stories/index.html.erb
<div class = "story-index">
  <h4>  Here is our list of stories from all over Sydney </h4>


  <table style="width:50%">
    <tr>
      <th>Story</th>
      <th>User</th>
    </tr>
    <% @stories.each do |story| %>
      <tr>
        <td><%= link_to story.title, story_path(story.id) %></td>
        <td>by <%= story.user.name %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/stories/new.html.erb
<div class="new-story col-xs-4 col-xs-offset-4">
    <h2>Create New Story</h2>

    <!-- <form class="form-horizontal"> -->

    <%= form_for @story, html: {class:"form-horizontal"} do |f| %>

    <div class="form-group">
        <%= f.label :title  %>
        <%= f.text_field :title, :autofocus => true, :required => true, :placeholder =>"Title"%>
    </div>

    <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, :required => true, :placeholder =>"Enter your story here",:class =>"form-control",:rows =>"15"%>
    </div>

    <div class="form-group">
        <%= f.submit "share this story", :class =>"btn btn-danger"%>
    </div>

    <% end %>

</div>

app/views/stories/show.html.erb
<div class ="story-show" >

<h1><%= @story.title %></h1>
<h3><%= @story.likes.count %> <span class="glyphicon glyphicon-glass"></span> </h3>
<p>created on <%= @story.created_at.strftime '%A %B %e, %Y' %></p>
<p>updated on <%= @story.updated_at.strftime '%A %B %e, %Y' %></p>
<p>location: <%= @story.address %></p>
<from ><%= @story.content %></form >


<% if @current_user.present?%>

  <% if @current_user.likes.where(:story_id => @story.id).empty? %>
    <%= link_to  "whisky", like_path(@story.id), :method => :post %>
  <% else %>
    <%= link_to "unwhisky", unlike_path(@story.id), :method => :post %>
  <% end %>
<% else %>
  <p><%= link_to("Log in to whiskey this story!", login_path) %> </p>
<% end %>

<% if @current_user.present? && @story.user_id == @current_user.id %>
  <%= link_to "Edit", edit_story_path(@story.id) %>
  <%= link_to "Delete Story", @story, method: :delete, data: { confirm: 'Are you sure?' }  %>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="sign-up col-xs-4 col-xs-offset-4">

<h1>Edit user</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ol>
<% end %>



<%= form_for @user  do |f| %>
    <div class ="form-group">
        <%= f.label :email,:class => "control-label" %>
        <%= f.text_field :email, :autofocus => true, :required => true,  :class => 'form-control' %>
    </div>

    <div class ="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class => 'form-control' %>
    </div>

    <div class ="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class => 'form-control'  %>
    </div>

    <%= f.submit  %>
  <% end %>



</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
  <div class="sign-up col-xs-4 col-xs-offset-4">

    <h4>Sign Up <span class="glyphicon glyphicon-paperclip"></span></h4>

    <% if @user.errors.any? %>
      <ol>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ol>
    <% end %>

    <%= form_for @user do |f| %>

      <div class ="form-group">
          <%= f.label :name, :class => "control-label"%>
          <%= f.text_field :name, :required => true, :class => 'form-control' %>
      </div>


      <div class ="form-group">
          <%= f.label :email, :class => "control-label"%>
          <%= f.text_field :email, :autofocus => true, :required => true, :class => 'form-control' %>
      </div>

      <div class="form-group">
          <%= f.label :password, :class => "control-label" %>
          <%= f.password_field :password, :class =>'form-control' %>
      </div>

      <div class="form-group">
          <%= f.label :password_confirmation, :class => "control-label" %>
          <%= f.password_field :password_confirmation, :class => 'form-control' %>
      </div>

      <%= f.submit "Sign up", :class =>"btn btn-danger" %>
    <% end %>
  </div>

app/views/users/show.html.erb
<h2>you are logged in as: <%= @user.name %></h2>
<p><%= link_to "edit your profile", edit_user_path %></p>


<div class = "user-show">
<p>you have posted these stories :</p>

<table style="width:100%" class="table-striped">

<% @user.stories.each do |story| %>
<tr>
  <td><%= link_to story.title, story_path(story.id) %></td>
  <td><%= link_to 'Edit', edit_story_path(@user) %> <%= link_to 'Delete', @story, :method => :delete, :data => { :confirm => "Are you sure?" } %></td>
  <% end %>
  </table>

</div>


</br>

<p><%= link_to "add more stories...", new_story_path %></p>